version: "3"

services:
  # Bot
  app:
    container_name: tracker_bot
    build: .
    restart: always
    depends_on:
      - db
    links:
      - db

  # MariaDB
  db:
    image: mariadb:bionic
    container_name: tracker_db
    env_file: .env
    restart: always
    ports:
     - ${MYSQL_PORT}:3306
    volumes:
      - './mariadb_data:/data/mariadb'

  # PhpMyAdmin
  phpmyadmin:
    image: jackgruber/phpmyadmin:latest
    container_name: tracker_phpmyadmin
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - ${PMA_PORT}:80

volumes:
  mariadb:
    driver: local